library(forecast)
library(quantmod)
library(caret)

getSymbols('MANU',src='yahoo',from=as.Date("2016-06-30"),to=as.Date("2018-06-30"))

lmFit<-tslm(ts(MANU [,'MANU.Adjusted']) ~ trend)
etsFit<-ets(ts(MANU [,'MANU.Adjusted']))
arimaFit<-auto.arima(ts(MANU [,'MANU.Adjusted']))
nnFit<-nnetar(ts(MANU[,'MANU.Adjusted']))
linForecast<-forecast(lmFit,h=31)
etsForecast<-forecast(etsFit,h=31)
arimaForecast<-forecast(arimaFit,31)
nnForecast<-forecast(nnFit,31)
par(mfrow=c(2,2))
plot(linForecast,ylab='MANU Adjusted Closing Price',xlab='Trading Day, Starting 6/29/2016',main='Linear Trend Forecast')
abline(lmFit,lty=2,col='red')
plot(etsForecast,ylab="MANU Adjusted Closing Price", xlab='Trading Day, Starting 6/29/2016',main='Exponential Smoothing (ETS) Forecast')
plot(arimaForecast,ylab="MANU Adjusted Closing Price", xlab='Trading Day, Starting 6/29/2016',main='ARIMA Forecast')
plot(nnForecast,ylab="MANU Adjusted Closing Price", xlab='Trading Day, Starting 6/29/2016',main='NNETAR Forecast')